kind: Deployment
apiVersion: apps/v1
metadata:
  name: javaspb
  labels:
    app: javaspb
    app.kubernetes.io/component: javaspb
    app.kubernetes.io/instance: javaspb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspb
  template:
    metadata:
      labels:
        app: javaspb
    spec:
      containers:
        - name: javaspb
          image: docker.io/nagendrarb/java-spring-boot:v1
          ports:
            - containerPort: 8181
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600